---
- name: Transfer and execute a script.
  hosts: all
  become: true
  become_user: postgres
  tasks:

     - set_fact:
         pgbench_logfile: pgbench_read_test_{{ test_id }}_sc_{{ stripe_count }}_ss_{{ stripe_size }}.log
         dstat_logfile: dstat_{{ test_id }}_sc_{{ stripe_count }}_ss_{{ stripe_size }}.log

     - name: Transfer the script
       ansible.builtin.copy: src=pgbench_read_test.sh dest=/var/lib/postgresql/pgbench_read_test.sh mode='0700'

     - name: Start the system stats logger
       ansible.builtin.shell: nohup dstat -tcd --io 60 &> /var/lib/postgresql/{{ dstat_logfile }} & echo $! >/tmp/pgbench_read_test_os_stats_logger.pid
       args:
         executable: /bin/bash

     - name: Run the test script
       ansible.builtin.shell: /var/lib/postgresql/pgbench_read_test.sh {{ pgbench_scale | d(1) }} {{ pgbench_duration | d(5) }} {{ cpus | d(ansible_processor_vcpus) }} &> {{ pgbench_logfile }}
       args:
         executable: /bin/bash
         chdir: /var/lib/postgresql
       async: 14400
       poll: 60

     - name: Kill the iostat logger process
       ansible.builtin.shell: kill -9 $(cat /tmp/pgbench_read_test_os_stats_logger.pid)
       args:
         executable: /bin/bash

     - name: Pull run logs
       ansible.builtin.fetch:
         src: /var/lib/postgresql/{{ pgbench_logfile }}
         dest: ./logs/{{ pgbench_logfile }}
         flat: true
         fail_on_missing: true

     - name: Pull run logs - iostats
       ansible.builtin.fetch:
         src: /var/lib/postgresql/{{ dstat_logfile }}
         dest: ./logs/{{ dstat_logfile }}
         flat: true
         fail_on_missing: true
