---
- name: Transfer and execute a script.
  hosts: all
  become: true
  become_user: postgres
  tasks:

#     - name: Vars
#       debug:
#         var: pgbench_duration

     - set_fact:
         pgbench_logfile: pgbench_read_test_sc_{{ stripe_count }}_ss_{{ stripe_size }}_full.log
     - name: Transfer the script
       ansible.builtin.copy: src=pgbench_read_test.sh dest=/var/lib/postgresql/pgbench_read_test.sh mode='0700'

     - name: Run the test script
       ansible.builtin.shell: /var/lib/postgresql/pgbench_read_test.sh {{ pgbench_scale | d(1) }} {{ pgbench_duration | d(5) }} {{ cpus | d(ansible_processor_vcpus) }} &> {{ pgbench_logfile }}
       args:
         executable: /bin/bash
         chdir: /var/lib/postgresql
       async: 7200
       poll: 30

     - name: Pull run logs
       ansible.builtin.fetch:
         src: /var/lib/postgresql/{{ pgbench_logfile }}
         dest: ./logs/{{ pgbench_logfile }}
         flat: true
         fail_on_missing: true
